# Generated by Django 5.0.1 on 2024-02-13 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0003_tbl_organ'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_bloodgroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bloodgroup_name', models.CharField(max_length=20)),
            ],
        ),
    ]
