# Generated by Django 5.0.1 on 2024-01-30 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=20)),
                ('user_email', models.CharField(max_length=20)),
                ('user_contact', models.CharField(max_length=20)),
                ('user_address', models.CharField(max_length=20)),
                ('user_gender', models.CharField(max_length=20)),
                ('user_district', models.CharField(max_length=20)),
                ('user_place', models.CharField(max_length=20)),
                ('user_proof', models.FileField(upload_to='user/')),
            ],
        ),
    ]
