# Generated by Django 5.0.1 on 2024-01-30 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_email', models.CharField(max_length=20)),
                ('login_password', models.CharField(max_length=20)),
            ],
        ),
    ]
