# Generated by Django 5.0.1 on 2024-02-13 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0003_delete_tbl_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=20)),
                ('user_email', models.CharField(max_length=20)),
                ('user_contact', models.CharField(max_length=20)),
                ('user_address', models.CharField(max_length=20)),
                ('user_district', models.CharField(max_length=20)),
                ('user_place', models.CharField(max_length=20)),
                ('user_photo', models.FileField(upload_to='user/')),
                ('user_proof', models.FileField(upload_to='user/')),
                ('user_password', models.CharField(max_length=20)),
            ],
        ),
    ]
