# Generated by Django 5.0.1 on 2024-02-13 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0004_tbl_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_name', models.CharField(max_length=20)),
                ('hospital_email', models.CharField(max_length=20)),
                ('hospital_contact', models.CharField(max_length=20)),
                ('hospital_address', models.CharField(max_length=20)),
                ('hospital_district', models.CharField(max_length=20)),
                ('hospital_place', models.CharField(max_length=20)),
                ('hospital_logo', models.FileField(upload_to='user/')),
                ('hospital_proof', models.FileField(upload_to='user/')),
                ('hospital_password', models.CharField(max_length=20)),
            ],
        ),
    ]
