# Generated by Django 5.0.1 on 2024-02-19 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0005_tbl_hospital'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_login',
        ),
    ]
