# Generated by Django 5.0.1 on 2024-02-19 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0006_tbl_notification'),
        ('Guest', '0006_delete_tbl_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_user',
            name='user_place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_place'),
        ),
    ]
