# Generated by Django 5.0.1 on 2024-02-20 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0006_tbl_notification'),
        ('Guest', '0007_alter_tbl_user_user_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_hospital',
            name='hospital_place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_place'),
        ),
    ]
