# Generated by Django 5.0.1 on 2024-03-08 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0008_alter_tbl_hospital_hospital_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_hospital',
            name='hospital_logo',
            field=models.FileField(upload_to='hospital/'),
        ),
        migrations.AlterField(
            model_name='tbl_hospital',
            name='hospital_proof',
            field=models.FileField(upload_to='hospital/'),
        ),
    ]
